@extends('layouts.app')
@section('content')
<div class="app-shell">
    <header class="topbar"><div><p class="eyebrow">PERBAIKI CATATAN</p><h1>Edit transaksi</h1></div><a class="avatar avatar-link" href="{{ route('dashboard') }}">⌂</a></header>
    <main class="content">
        <form method="POST" action="{{ route('transactions.update', $transaction) }}" class="sheet-content transaction-edit-form">@csrf @method('PUT')<label>Jenis<select name="type" id="edit-transaction-type"><option value="expense" @selected($transaction->type === 'expense')>Pengeluaran</option><option value="income" @selected($transaction->type === 'income')>Pemasukan</option><option value="transfer" @selected($transaction->type === 'transfer')>Transfer</option></select></label><label id="edit-account-label">{{ $transaction->type === 'income' ? 'Masuk ke akun' : 'Dari akun' }}<select name="account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($transaction->account_id === $account->id)>{{ $account->name }}</option>@endforeach</select></label><label id="edit-destination-field" @if($transaction->type !== 'transfer') hidden @endif>Ke akun<select name="destination_account_id">@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($transaction->destination_account_id === $account->id)>{{ $account->name }}</option>@endforeach</select></label><label>Nominal<input type="number" name="amount" min="1" value="{{ $transaction->amount }}" required></label><label>Kategori<select name="category_id"><option value="">Tanpa kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($transaction->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Tanggal<input type="date" name="transaction_date" value="{{ $transaction->transaction_date->format('Y-m-d') }}" required></label><label>Catatan<input name="note" maxlength="255" value="{{ $transaction->note }}" placeholder="Contoh: makan siang"></label><div class="edit-actions"><a class="button button-quiet" href="{{ route('dashboard') }}">Batal</a><button class="button button-primary" type="submit">Simpan perubahan</button></div></form>
    </main>
</div>
@endsection
@push('scripts')<script>const editType=document.querySelector('#edit-transaction-type');const editAccountLabel=document.querySelector('#edit-account-label');const editDestination=document.querySelector('#edit-destination-field');function toggleEditFields(){editDestination.hidden=editType.value!=='transfer';editDestination.style.display=editType.value==='transfer'?'grid':'none';editAccountLabel.firstChild.textContent=editType.value==='income'?'Masuk ke akun':'Dari akun';}editType.addEventListener('change',toggleEditFields);toggleEditFields();</script>@endpush
