@extends('layouts.app')
@section('content')
<div class="app-shell more-page-compact">
    <header class="topbar"><div><p class="eyebrow">RUANG KAMU</p><h1>Pengaturan</h1></div><div class="avatar">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</div></header>
    <main class="content">
        <section class="profile-strip"><div class="avatar profile-avatar">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</div><div><strong>{{ auth()->user()->name }}</strong><small>{{ auth()->user()->email }}</small></div></section><a class="settings-row profile-settings-row" href="{{ route('settings') }}"><span class="menu-icon">⚙</span><div><strong>Profil</strong><small>{{ auth()->user()->currency }} · {{ auth()->user()->email }}</small></div><b>›</b></a>
        <p class="eyebrow settings-group-label">FITUR UTAMA</p><div class="menu-list"><a class="menu-row" href="{{ route('goals') }}"><span class="menu-icon">◎</span><div><strong>Target tabungan</strong><small>{{ $goalCount }} target aktif</small></div><b>›</b></a><a class="menu-row" href="{{ route('budgets') }}"><span class="menu-icon">▣</span><div><strong>Anggaran bulanan</strong><small>Atur batas pengeluaran</small></div><b>›</b></a><a class="menu-row" href="{{ route('recurring') }}"><span class="menu-icon">↻</span><div><strong>Transaksi berulang</strong><small>Gaji dan tagihan rutin</small></div><b>›</b></a><a class="menu-row" href="{{ route('debts') }}"><span class="menu-icon">↔</span><div><strong>Hutang & Piutang</strong><small>Catat pinjaman dan pelunasan</small></div><b>›</b></a><a class="menu-row" href="{{ route('reports') }}"><span class="menu-icon">◒</span><div><strong>Laporan</strong><small>Lihat pola arus uang</small></div><b>›</b></a></div>
        <div class="menu-list management-links"><a class="menu-row" href="{{ route('accounts') }}"><span class="menu-icon">▣</span><div><strong>Akun bank</strong><small>{{ $accounts->count() }} akun aktif</small></div><b>›</b></a><a class="menu-row" href="{{ route('categories') }}"><span class="menu-icon">●</span><div><strong>Kategori</strong><small>{{ $categories->count() }} kategori aktif</small></div><b>›</b></a></div>
        <section class="data-tools"><div class="section-heading"><div><p class="eyebrow">DATA</p><h2>Backup</h2></div></div><div class="data-tool-actions"><a class="button button-quiet" href="{{ route('backup') }}">Download backup</a><form method="POST" action="{{ route('backup.restore') }}" enctype="multipart/form-data"><input type="file" name="backup" accept=".json,application/json" required><button class="button button-quiet" type="submit">Pulihkan backup</button>@csrf</form></div></section>
        <form method="POST" action="{{ route('logout') }}" class="logout-form">@csrf<button class="button button-quiet" type="submit">Keluar dari akun</button></form>
    </main>
    <nav class="bottom-nav"><a href="{{ route('dashboard') }}"><span>⌂</span>Home</a><a href="{{ route('reports') }}"><span>◒</span>Laporan</a><a class="nav-plus" href="{{ route('dashboard') }}#transaction-sheet">+</a><a href="{{ route('goals') }}"><span>◎</span>Target</a><a class="active" href="{{ route('more') }}"><span>•••</span>Pengaturan</a></nav>
</div>
@endsection
