<article class="debt-card {{ $debt->type === 'receivable' ? 'receivable' : '' }} {{ $debt->status === 'settled' ? 'settled' : '' }}">
    <div class="debt-top"><span class="debt-icon">{{ $debt->type === 'receivable' ? '↗' : '↙' }}</span><div><strong>{{ $debt->person }}</strong><small>{{ $debt->type === 'receivable' ? 'Piutang' : 'Hutang' }}{{ $debt->status === 'settled' ? ' · Lunas' : '' }}</small></div><span class="debt-amount">{{ number_format($debt->amount, 0, ',', '.') }}</span></div>
    <div class="debt-progress"><span style="width: {{ min(100, ($debt->paid_amount / max(1, $debt->amount)) * 100) }}%"></span></div>
    <div class="debt-payment-summary"><span>Terbayar {{ number_format($debt->paid_amount, 0, ',', '.') }}</span><strong>Sisa {{ number_format($debt->remaining_amount, 0, ',', '.') }}</strong></div>
    <div class="debt-meta"><span>{{ $debt->due_date ? 'Jatuh tempo '.$debt->due_date->format('d M Y') : 'Tanpa jatuh tempo' }}</span>@if($debt->note)<span>{{ $debt->note }}</span>@endif</div>
    @if($debt->payments->isNotEmpty())<details class="payment-history"><summary>{{ $debt->payments->count() }} catatan pembayaran</summary>@foreach($debt->payments as $payment)<div><span>{{ $payment->paid_at->format('d M Y') }}{{ $payment->account ? ' · '.$payment->account->name : '' }}{{ $payment->note ? ' · '.$payment->note : '' }}</span><strong>{{ number_format($payment->amount, 0, ',', '.') }}</strong></div>@endforeach</details>@endif
    @if($debt->status === 'unpaid')<div class="debt-actions"><button type="button" onclick="document.querySelector('#payment-{{ $debt->id }}').showModal()">Catat cicilan</button><form method="POST" action="{{ route('debts.settle', $debt) }}">@csrf @method('PATCH')<button type="submit">Tandai lunas</button></form><form method="POST" action="{{ route('debts.destroy', $debt) }}" onsubmit="return confirm('Hapus catatan ini?')">@csrf @method('DELETE')<button class="debt-delete" type="submit">Hapus</button></form></div>@endif
</article>
@if($debt->status === 'unpaid')<dialog id="payment-{{ $debt->id }}" class="sheet"><form method="POST" action="{{ route('debts.payment', $debt) }}" class="sheet-content">@csrf<button type="button" class="sheet-close" onclick="this.closest('dialog').close()">×</button><p class="eyebrow">{{ strtoupper($debt->person) }}</p><h2>Catat cicilan</h2><p class="payment-remaining">Sisa yang perlu dibayar: <strong>{{ number_format($debt->remaining_amount, 0, ',', '.') }}</strong></p><label>{{ $debt->type === 'debt' ? 'Bayar dari akun' : 'Masuk ke akun' }}<select name="account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></label><label>Nominal pembayaran<input type="number" name="amount" min="1" max="{{ $debt->remaining_amount }}" required placeholder="0"></label><label>Tanggal pembayaran<input type="date" name="paid_at" value="{{ now()->format('Y-m-d') }}" required></label><label>Catatan<input name="note" maxlength="255" placeholder="Contoh: cicilan pertama"></label><button class="button button-primary" type="submit">Simpan cicilan</button></form></dialog>@endif
