@extends('layouts.app')
@section('content')
<div class="app-shell">
    <header class="topbar"><div><p class="eyebrow">RENCANA MASA DEPAN</p><h1>Target tabungan</h1></div><a class="avatar avatar-link" href="{{ route('dashboard') }}">⌂</a></header>
    <main class="content">
        @forelse($goals as $goal)
            <section class="goal-card" style="--goal-color: {{ $goal->color }}"><div class="goal-top"><span class="goal-icon">◎</span><div><h2>{{ $goal->name }}</h2><small>{{ $goal->deadline ? 'Sampai '.$goal->deadline->format('d M Y') : 'Tanpa deadline' }}</small></div><strong>{{ $goal->progress }}%</strong></div><div class="goal-progress"><span style="width: {{ $goal->progress }}%"></span></div><div class="goal-values"><span>{{ number_format($goal->saved_amount, 0, ',', '.') }} <small>terkumpul</small></span><span>{{ number_format($goal->target_amount, 0, ',', '.') }} <small>target</small></span></div><button class="button button-goal" type="button" onclick="document.querySelector('#contribute-{{ $goal->id }}').showModal()">+ Catat tabungan</button></section>
            <dialog id="contribute-{{ $goal->id }}" class="sheet"><form method="POST" action="{{ route('goals.contribute', $goal) }}" class="sheet-content">@csrf<button type="button" class="sheet-close" onclick="this.closest('dialog').close()">×</button><p class="eyebrow">{{ strtoupper($goal->name) }}</p><h2>Perbarui tabungan</h2><label>Aksi<select name="type" class="savings-action"><option value="deposit">Tambah tabungan</option><option value="withdrawal">Kurangi tabungan</option></select></label><label class="savings-account-label">Dari akun<select name="account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></label><label class="savings-destination-label">Masuk ke akun tabungan<select name="destination_account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></label><label>Nominal<input type="number" name="amount" min="1" required placeholder="0"></label><label>Catatan<input name="note" maxlength="255" placeholder="Contoh: setoran bulan ini"></label><button class="button button-primary" type="submit">Simpan perubahan</button></form></dialog>
        @empty
            <div class="empty-state goal-empty"><strong>Belum ada target.</strong><br><span>Buat target pertama untuk mengubah rencana menjadi langkah kecil.</span></div>
        @endforelse
        <button class="button button-primary full-button" type="button" onclick="document.querySelector('#new-goal').showModal()">+ Buat target baru</button>
    </main>
    <nav class="bottom-nav"><a href="{{ route('dashboard') }}"><span>⌂</span>Home</a><a href="{{ route('reports') }}"><span>◒</span>Laporan</a><a class="nav-plus" href="{{ route('dashboard') }}#transaction-sheet">+</a><a class="active" href="{{ route('goals') }}"><span>◎</span>Target</a><a href="{{ route('more') }}"><span>•••</span>Pengaturan</a></nav>
</div>
<dialog id="new-goal" class="sheet"><form method="POST" action="{{ route('goals.store') }}" class="sheet-content">@csrf<button type="button" class="sheet-close" onclick="this.closest('dialog').close()">×</button><p class="eyebrow">TARGET BARU</p><h2>Apa yang ingin kamu capai?</h2><label>Nama target<input name="name" required maxlength="100" placeholder="Contoh: Laptop baru"></label><label>Nominal target<input type="number" name="target_amount" min="1" required placeholder="0"></label><label>Deadline (opsional)<input type="date" name="deadline"></label><label>Warna<input type="color" name="color" value="#126E73"></label><button class="button button-primary" type="submit">Buat target</button></form></dialog>
@endsection
@push('scripts')<script>document.querySelectorAll('.savings-action').forEach(function(action){function toggleSavingsAccount(){const form=action.closest('form');form.querySelector('.savings-account-label').firstChild.textContent=action.value==='deposit'?'Dari akun':'Dari akun tabungan';form.querySelector('.savings-destination-label').firstChild.textContent=action.value==='deposit'?'Masuk ke akun tabungan':'Kembalikan ke akun';}action.addEventListener('change',toggleSavingsAccount);toggleSavingsAccount();});</script>@endpush